#!/usr/bin/env bash
# Check if an IP address is provided as an argument
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

ping -c 5 $ip_address

if [ $? -eq 0 ]; then
    echo "The host at $ip_address is reachable."
else
    echo "The host at $ip_address is not reachable."
fi
